// 每个已集成攻击的详细讲解。
export const categoryIntro = {
  webshell:
    "WebShell 是攻击者植入 Web 服务器的后门脚本，用于远程执行命令、管理文件。加密型 WebShell（如冰蝎）把命令和结果全部加密传输，传统基于明文特征和文件哈希的检测失效，只能在加密流量侧信道寻找行为指纹。",
  c2: "C2（命令与控制）框架是攻击者与受控主机之间的指挥通道。上线心跳、任务下发、结果回传都有固定节奏与格式，心跳周期、载荷结构和连接生命周期是最稳定的指纹。",
  tunnel:
    "隧道/内网穿透工具把外部流量伪装成正常通信（TLS/HTTP/ICMP/DNS）穿透边界，用于把内网服务暴露到外网或建立隐蔽 C2 通道。长连接、周期心跳、固定包长是常见指纹。",
  rat: "远控木马（RAT）是间谍/窃密武器，持续保持与 C2 的加密连接，定期回传主机信息，加密通信通常有固定握手格式和心跳周期。",
  apt: "APT 组织的攻击武器往往在开源工具基础上定制或自研私有协议，识别其加密通信特征需要在流量侧建立行为基线。",
};

export const attacks = [
  {
    id: "behinder",
    name: "冰蝎 Behinder",
    category: "webshell",
    article: 208,
    integrated: true,
    what: "冰蝎是一款动态二进制加密的 WebShell 管理工具，支持 JSP/PHP/ASPX。内存马版本通过中间件漏洞（Fastjson、Log4j、Spring EL）把 Agent 注入 JVM 内存，磁盘上不落任何文件。",
    why: "它让攻击者获得 Web 服务器的远程命令执行能力：读取敏感数据、内网横向、驻留持久化。所有 C2 流量走 TLS 加密，文件型检测完全失效——'看不见的攻击入口'正是它的危害核心。",
    how: "内存注入 → 每连接独立 AES 密钥协商 → 命令经 AES-GCM + Base64 封装为 HTTP POST → TLS 传输 → 服务端解密执行（Runtime.exec / Java IO）→ 结果加密回传。",
    fingerprint: [
      "一操作一连接：每条 TCP 流只做一次请求-响应（Connection: close）",
      "每条流 13±3 条 TLS 记录",
      "请求侧恒定 8225B 分块（okio 8192B 缓冲 + TLS 开销）",
      "请求大于响应；流间无重叠，间隔体现人操作节奏",
      "JA3 稳定（JDK11 + OkHttp TLS 栈）",
    ],
    rule: "behinder.mem_shell_flow / behinder.memory_shell_aggregate",
    charts: ["behinder_records_per_flow.png", "behinder_req_size_hist.png", "behinder_timeline.png"],
  },
  {
    id: "ligolo",
    name: "Ligolo-ng",
    category: "tunnel",
    article: 181,
    integrated: true,
    what: "Ligolo-ng 是一款 Go 编写的 TUN 隧道工具，通过反向 TCP/TLS 连接建立隐蔽通信信道，支持自签/Let's Encrypt 证书。",
    why: "它把受害内网的服务（RDP/SSH/任意 TCP）映射到攻击者的 TUN 网卡，等于在边界上开了一扇隐形门——攻防演练中用于内网横向移动，实际攻击中被用于建立持久 C2 通道。",
    how: "服务端（攻击机）监听 11601，客户端（受害机）校验证书指纹后建立 TLS 通道；上层用 yamux 多路复用，双端各自维护心跳保持通道活跃。",
    fingerprint: [
      "TLS 1.3 + AES-128-GCM（ServerHello cipher=0x1301）",
      "双向固定 29B 心跳记录（12B yamux ping + 1B 记录类型 + 16B GCM 标签）",
      "心跳周期固定：proxy 30s / agent 60s（旧版 27s/30s）",
      "先下行后上行（服务端先发请求，客户端回应）",
      "超长连接（分钟~小时级）",
    ],
    rule: "ligolo.tunnel_heartbeat",
    charts: ["ligolo_heartbeat_scatter.png", "ligolo_size_hist.png"],
  },
  {
    id: "suo5",
    name: "suo5",
    category: "tunnel",
    article: 162,
    integrated: true,
    what: "suo5 是一款高性能 HTTP 隧道代理工具，常用于配合 WebShell/内存马做全双工流量转发，v1.1 起每次握手随机化 TLS 指纹。",
    why: "它把 HTTP(S) 请求变成双向隧道，让攻击者能通过一个 WebShell 入口转发任意 TCP 流量（RDP/代理/C2），绕过基于流量的检测和出口管控。",
    how: "客户端连接 suo5.jsp/内存马端点 → 双向 chunked-encoding 流复用 → 5s 心跳保活 → SOCKS5 代理转发。v1.1+ 每次建立 TLS 连接随机选择密码套件与扩展，主动对抗 JA3 指纹检测。",
    fingerprint: [
      "同源多条短 TLS 流出现多个不同密码套件集合（JA3 随机化——反检测特征本身就是指纹）",
      "隧道建立后每 5s 一次心跳",
      "请求体为二进制流（Content-Type: application/octet-stream）",
    ],
    rule: "suo5.ja3_randomization（聚合）/ suo5.heartbeat",
    charts: ["suo5_scatter.png"],
  },
  {
    id: "merlin",
    name: "Merlin",
    category: "c2",
    article: 140,
    integrated: true,
    what: "Merlin 是一款 Go 编写的开源 C2 框架，使用 JWE（JSON Web Encryption）加密通信，支持 HTTP/HTTPS/HTTP2 等协议。",
    why: "它提供完整的后渗透能力（命令执行、文件操作、横向、代理），且默认流量即加密——JWE 让载荷在不解密的情况下完全不可读，是典型的'沉默的指挥通道'。",
    how: "Agent 上线携带 AgentID（JWT），服务端用 PSK（默认 'merlin'）验证；之后每次 checkin 是一个 JWE 加密的 HTTP POST，默认 sleep 30s ± 3s 抖动。",
    fingerprint: [
      "长连接 + 周期性整次交换（默认 30s ±3s）",
      "请求/响应均为 JWE 加密载荷（体积稳定）",
      "HTTP/2（h2）传输",
    ],
    rule: "merlin.polling",
    charts: ["merlin_scatter.png"],
  },
  {
    id: "stowaway",
    name: "Stowaway",
    category: "tunnel",
    article: 203,
    integrated: true,
    what: "Stowaway 是一款 Go 编写的多级代理工具，用于突破内网访问限制，支持多级节点和丰富的功能模块。",
    why: "攻击者用它搭建多级代理链，把流量逐级跳转隐藏真实来源；即使某一级被发现，上级和真实 C2 仍然隐蔽。",
    how: "连接建立后 1 秒内完成预认证：Agent 发送 16 字节 AuthToken（MD5(secret)[:16]），Admin 原样回显；之后所有载荷按 36 字节头 + Gzip + AES-256-GCM 加密传输，并保持单向心跳。",
    fingerprint: [
      "非 TLS 明文 TCP 协议（自有加密）",
      "首个客户端载荷 16B + 首个服务端载荷 16B（AuthToken 回显，1s 内）",
      "加密帧有固定 36 字节头 + 28 字节 GCM 开销",
      "周期心跳保持通道",
    ],
    rule: "stowaway.auth_token_handshake / stowaway.heartbeat",
    charts: ["stowaway_scatter.png"],
  },
  {
    id: "natpass",
    name: "natpass",
    category: "tunnel",
    article: 170,
    integrated: true,
    what: "natpass 是一款轻量级内网穿透工具，支持 Shell 管理、VNC 等，服务端默认监听 6154，支持 TLS 与自定义预共享密钥。",
    why: "被滥用为隐蔽通道：控制端经公网服务端连接内网受控端，把内网主机变成可随时远程操作的跳板；其自定义 Protobuf 协议让传统 DPI 无法解析。",
    how: "受控端上线先发 Protobuf 编码握手包（含 'remote'/'server' 标识，约 86B+），随后维持长连接并周期发送 keepalive 保持通道。",
    fingerprint: [
      "非 TLS 明文 TCP（默认配置）",
      "首包为 Protobuf 握手（60-200B，含固定 'remote'/'server' 字符串）",
      "长连接 + 周期 keepalive 小包",
    ],
    rule: "natpass.handshake / natpass.keepalive",
    charts: ["natpass_scatter.png"],
  },
  {
    id: "frp",
    name: "frp",
    category: "tunnel",
    article: 20,
    integrated: true,
    what: "frp 是高性能反向代理/内网穿透工具，frps（服务端）+ frpc（客户端）通过控制通道管理代理，可启用 TLS 加密。",
    why: "攻击者用它把内网服务（RDP、Web、SMB）映射到外网，或建立隐蔽 C2 中继；其 TLS 控制通道与正常业务流量难以区分，是攻防演练中高频使用的穿透工具。",
    how: "frpc 与 frps 建立 TLS 控制连接，注册代理规则；控制通道默认每 30s 发送一次心跳（transport.heartbeatInterval），心跳为固定小包。",
    fingerprint: [
      "TLS 长连接（控制通道）",
      "固定 30s 周期心跳（29B 小记录，双向）",
      "心跳大小稳定，间隔无抖动",
    ],
    rule: "frp.heartbeat",
    charts: ["frp_scatter.png"],
  },
  {
    id: "sliver",
    name: "Sliver",
    category: "c2",
    article: 140,
    integrated: true,
    what: "Sliver 是 BishopFox 开源的跨平台 C2 框架，支持 mTLS/HTTP(S)/DNS 等多种传输，beacon 模式默认 30s 检查间隔加抖动。",
    why: "作为新一代开源 C2，它被 APT 与红队广泛采用：mTLS 双向认证 + 加密 beacon 让 C2 流量高度隐蔽，且默认反制常见检测。",
    how: "生成植入体时内嵌服务端证书公钥；植入体以 beacon 模式周期性回连（默认 30s ± 抖动），每次 checkin 为一次加密交换，服务端下发任务、植入体回传结果。",
    fingerprint: [
      "mTLS（双向证书）长连接",
      "beacon 周期 ~30s（± 抖动），TLS 小记录",
      "连接会话持续在线，无正常业务流量特征",
    ],
    rule: "sliver.beacon",
    charts: ["sliver_scatter.png"],
  },
  {
    id: "gost",
    name: "gost",
    category: "tunnel",
    article: 12,
    integrated: true,
    what: "gost（Go Simple Tunnel）是多协议隧道工具，支持 TCP/UDP/WS/mTLS 等转发方式；观成文章分析的是其 ICMP 隐蔽隧道用法。",
    why: "攻击者常用 gost 搭建中继隧道转发 C2/横向流量：其 ws 中继把每一次转发的请求封装成新的 WebSocket 短连接，形成规律性的短流模式，可绕过基于单条长连接的检测。",
    how: "gost 客户端监听本地端口，把流量经 WebSocket 转发到远端 gost 服务端；每次转发建立一个短 ws 连接（HTTP Upgrade + 双向小帧），转发完成后立即关闭。",
    fingerprint: [
      "非 TLS 明文 WebSocket 中继（ws://）",
      "同源同目标周期性出现多条短流（间隔固定，本实验 8s 泵一次 beacon 流量）",
      "每条短流双向各 1-2 个小包（HTTP Upgrade ~190B + 中继小帧）",
      "流时长极短（<1s），无长连接",
    ],
    rule: "gost.tunnel_relay（聚合）/ gost.keepalive",
    charts: ["gost_scatter.png"],
  },
  {
    id: "platypus",
    name: "Platypus",
    category: "c2",
    article: 174,
    integrated: true,
    what: "Platypus 是多会话反向 Shell 管理器：Termite 监听器通过 HTTP 下发木马，木马随后用 TLS 回连，会话建立后进入交互式 Shell 模式。",
    why: "它让攻击者集中管理大量受害主机并实时执行命令；TLS 加密回连让 C2 通道在流量侧高度隐蔽，是红队与真实攻击者都常用的反向 Shell 平台。",
    how: "v1.5 采用安装令牌注册制：服务端签发 plt_ 一次性令牌，agent 携带令牌与项目 CA 完成 mTLS 注册，随后保持长连接并周期交换 RPC 消息（sys_info 等）。",
    fingerprint: [
      "TLS 长连接（agent 直连 ingress）",
      "注册后周期小 RPC 交换",
      "连接会话持续在线，无正常业务流量特征",
    ],
    rule: "platypus.link",
    charts: ["platypus_scatter.png"],
  },
  {
    id: "metasploit",
    name: "Metasploit",
    category: "c2",
    article: 5,
    integrated: true,
    what: "Metasploit 是最流行的渗透测试框架，meterpreter_reverse_https 是其标志性 C2 传输：HTTPS 加密回连 + TLV 协议。",
    why: "作为攻击面最广的 C2 载体，APT 和黑产都直接或间接使用 MSF 生成的木马；meterpreter 会话一旦建立，攻击者就获得了受害主机的完整控制能力。",
    how: "msfvenom 生成反向 HTTPS 载荷 → 载荷运行时与 handler 建立 TLS 连接 → 会话初始化阶段短时间内打开大量短连接（加载扩展、同步系统信息）→ 之后周期性通信。",
    fingerprint: [
      "同端点 10 秒内出现 15+ 条短 TLS 连接（会话初始化突发）",
      "每条短流 <1s，之后转入周期性轮询",
      "TLS 加密，无明文特征",
    ],
    rule: "metasploit.meterpreter（突发聚合）",
    charts: ["metasploit_scatter.png"],
  },
  {
    id: "weevely",
    name: "Weevely",
    category: "webshell",
    article: 1,
    integrated: true,
    what: "Weevely 是 Python 编写的 PHP WebShell 管理框架：生成混淆的 PHP 一句话后门，攻击者通过命令行交互式执行命令。",
    why: "它是攻防演练与真实攻击中最低门槛的 webshell 工具之一：只需上传一个 PHP 文件就能获得命令执行权限，流量被刻意混淆以绕过 WAF 与静态检测。",
    how: "weevely 客户端每次命令操作向后门发送混淆的 HTTP POST（内置加密/编码器），后门解密执行并回传结果；每条命令产生 2-3 条短连接，命令间隔体现操作节奏。",
    fingerprint: [
      "非 TLS 明文 HTTP（默认）",
      "同端点重复短流：每条流 <1s，请求 400-700B、响应 ~220B",
      "命令间隔 2-30s（人操作节奏）",
    ],
    rule: "weevely.interactive_shell（短流聚合）",
    charts: ["weevely_scatter.png"],
  },
  {
    id: "deimos",
    name: "DeimosC2",
    category: "c2",
    article: 8,
    integrated: true,
    what: "DeimosC2 是一款 Go 编写的 C2 框架（已停维护），支持 TCP/HTTPS/DoH/QUIC 四种 agent 通信方式，服务端带 Vue 前端做会话管理。",
    why: "它把受害主机的控制权交给攻击者：agent 每 15s 用一条新 TCP 连接回来登记心跳，所有报文用 RSA-OAEP + AES-256-CBC 双层加密，传统 DPI 无法解密，是典型的'沉默指挥通道'。",
    how: "agent 启动先发 init：8 字节大端长度 + 256B RSA-OAEP 块（1B 类型 + 36B agentKey + 32B AES 会话密钥）+ AES-CBC 系统信息；服务端回 8B 长度 + AES 加密的 agentKey。之后每 15s 用新连接 check-in，报文固定 296B 请求 / 40B 响应。",
    fingerprint: [
      "非 TLS TCP（自有 RSA+AES 加密）",
      "首包 = 8B 长度 + 256B RSA-OAEP + AES-CBC，大小恒为 8+16k（模 16 余 8）",
      "init 568B/72B，check-in 296B/40B",
      "每 ~15s 一条短连接（周期 check-in）",
    ],
    rule: "deimos.checkin / deimos.periodic_checkin",
    charts: ["deimos_scatter.png"],
  },
  {
    id: "xiebro",
    name: "XiebroC2",
    category: "c2",
    article: 0,
    integrated: true,
    what: "XiebroC2 是 Go 客户端 + .NET 8 Teamserver 的 C2 框架，支持 TCP/WebSocket 上线、反弹 Shell、文件管理、内存加载等，被描述为'轻量级 Cobalt Strike'。",
    why: "其 Linux TCP 客户端上线后保持一条长连接，每 15s 发送固定的 ClientPing 保活；报文是 AES-128-ECB 加密的 MessagePack，固定明文造成固定密文——这是最强的反检测特征之一。",
    how: "客户端连接 4B 小端长度前缀 + AES-128-ECB（固定 key）加密帧；首帧 ClientInfo（352B），之后每 15s 一个 ClientPing（48B 密文），服务端从不回包。",
    fingerprint: [
      "非 TLS 单条长连接",
      "C→S 每 15s [4B LE 长度][48B AES-ECB 密文]",
      "ClientPing 固定明文→固定密文（逐字节相同）",
      "S→C 零回包",
    ],
    rule: "xiebro.heartbeat",
    charts: ["xiebro_scatter.png"],
  },
  {
    id: "godzilla",
    name: "哥斯拉 Godzilla",
    category: "webshell",
    article: 149,
    integrated: true,
    what: "哥斯拉是一款 Java 编写的动态二进制加密 WebShell 管理工具，支持 PHP/JSP/ASPX/C#，payload 和加密方式均可自定义。",
    why: "它把 WebShell 流量做成'先上传 payload 进会话、再按需调用'的形态：传统 WAF 只看到一团 base64，看不到命令；会话式设计让每一条连接都很短，规避长连接检测。",
    how: "首条请求把 39KB payload.php 以 XOR+base64 上传进 PHP session；后续每次操作发 406B 的 XOR+base64 POST（methodName=getBasicsInfo 等），服务端回包用 md5(pass+key) 前后包裹。",
    fingerprint: [
      "非 TLS HTTP（默认 php_xor_base64）",
      "首条 53KB payload 上传（进 session）",
      "后续 406B XOR+base64 POST → 1.1-1.5KB 响应",
      "响应带 md5(pass+key) 前 16 位/后 16 位包裹",
      "操作间隔 1-5s（人操作节奏）",
    ],
    rule: "godzilla.payload_upload / godzilla.php_flow / godzilla.interactive_session",
    charts: ["godzilla_scatter.png"],
  },
  {
    id: "sish",
    name: "sish",
    category: "tunnel",
    article: 104,
    integrated: true,
    what: "sish 是 Go 编写的 SSH 反向隧道服务器：攻击者用一条 ssh -R 把内网服务映射到公网，支持 HTTP(S)/WS/TCP 多种转发。",
    why: "它把'外网可访问的内网端口'变成现实：一条 SSH 长连接就能把 RDP、Web、任意 TCP 服务暴露出去，且 SSH 流量本身加密，边界设备看到的只是 22 端口的一条普通 SSH 会话。",
    how: "ssh -R 8080:localhost:9090 tcp@sish-server → sish 在本地绑定 8080 并建立 SSH 控制通道；外部访问 8080 时流量经 SSH 通道回到客户端再转发到内网服务；双方每 5s 互发保活。",
    fingerprint: [
      "非 TLS 长连接（SSH 自加密）",
      "双向每 ~5s 28/52B 保活小包",
      "服务端动态绑定转发端口",
      "连接驻留时间长（分钟级）",
    ],
    rule: "sish.ssh_tunnel",
    charts: ["sish_scatter.png"],
  },
  {
    id: "shadowtls",
    name: "Shadow-TLS",
    category: "tunnel",
    article: 18,
    integrated: true,
    what: "Shadow-TLS 是一种 TLS 伪装隧道：在代理流量外面套一层'真实 TLS 握手'，让中间设备以为你在访问 GitHub/Cloudflare 等正常站点。",
    why: "它的核心思想是'借壳'——用真实站点的 ServerHello 完成握手，防火墙看到的 SNI、证书、加密套件全部来自正常网站，TLS-in-TLS 检测和 IP 信誉检测都失效。",
    how: "shadow-tls client 向 server 发起一个针对 github.com 的 TLS 握手，server 把 ClientHello 拼接转发给真实 github.com 完成握手；之后真正的代理数据混在固定大小的小记录里传输。",
    fingerprint: [
      "TLS 1.3 握手，SNI 指向常见站点",
      "ClientHello 仅 ~240B（浏览器/curl 通常 500B+）",
      "ServerHello ~127B（真实站点回包）",
      "握手后 app-data 记录为固定小尺寸",
    ],
    rule: "shadowtls.camouflage",
    charts: ["shadowtls_scatter.png"],
  },
  {
    id: "abptts",
    name: "ABPTTS",
    category: "tunnel",
    article: 15,
    integrated: true,
    what: "ABPTTS（A Black Path Toward The Sun）是 NCC Group 的 HTTP 加密隧道：把任意 TCP 流量封装进 HTTP POST，服务器端是 JSP/ASPX 木马。",
    why: "它专门用于'只有 WebShell 出口'的内网环境：RDP、SSH、Meterpreter 都能塞进 HTTP 请求里出网，且流量用 AES 加密、参数名和响应串每次生成都随机化，传统特征库抓不住。",
    how: "客户端把 TCP 流切块，每条连接发一次 POST（随机 accessKey header + AES-CBC 加密参数），服务端 JSP 建立到目标端口的 socket 并回传数据；响应包在伪装成'System Status API'的 HTML 里。",
    fingerprint: [
      "非 TLS HTTP，每条连接一次 POST 到同一 JSP",
      "随机 accessKey header（每次部署不同）",
      "AES-CBC 加密参数：请求 500-800B / 响应 280-600B",
      "响应带伪 'System Status API' HTML 前后缀",
      "连续多条短流（开/发/收/关 4 连击）",
    ],
    rule: "abptts.tunnel_post",
    charts: ["abptts_scatter.png"],
  },
  {
    id: "antsword",
    name: "蚁剑 AntSword",
    category: "webshell",
    article: 1,
    integrated: true,
    what: "蚁剑是中国蚁剑（AntSword）开源跨平台 WebShell 管理器，Node.js 编写，支持 PHP/JSP/ASPX 等多种载荷与编码器。",
    why: "它是攻防演练和真实入侵中最常见的 WebShell 管理工具之一：一句话木马 + 加密编码器让命令执行流量难以被静态特征匹配；其'随机变量名 + base64 代码 + 随机 hex tag'的组合是稳定指纹。",
    how: "POST 两个参数：密码参数 = @eval(@base64_decode($_POST['随机名']))；随机名参数 = base64(压缩后的 PHP 模板代码)。响应 = 随机 hex tag + 明文输出 + 随机 hex tag。",
    fingerprint: [
      "非 TLS HTTP（默认 PHP）",
      "每操作一条短连接（<3s）",
      "请求 ~2.1KB：296B 头 + 1.8KB base64 代码",
      "响应 ~305B：随机 hex tag 包裹明文输出",
      "操作间隔 1-5s（人操作节奏）",
    ],
    rule: "antsword.php_flow",
    charts: ["antsword_scatter.png"],
  },
  {
    id: "covenant",
    name: "Covenant",
    category: "c2",
    article: 133,
    integrated: true,
    what: "Covenant 是 .NET 编写的开源 C2 框架：服务端带 Web UI，grunt（植入体）用 .NET Core 编写，支持 HTTP/HTTPS 与 SMB 两种通信。",
    why: "它是红队与真实攻击者中高频使用的 C2：grunt 通过看似正常的'网页 profile'URL（/en-us/index.html）回连，请求体是 AES 加密的 JSON + HMAC 校验，传统 DPI 只能看到一团 base64 参数。",
    how: "grunt 启动走三阶段注册：Stage0 上传 RSA 公钥 → Stage1 应答挑战 → Stage2 植入体上线；之后按 delay（默认 3-5s）周期 check-in。每次请求格式：i=<32hex>&data=<base64 {GUID,Type,IV,EncryptedMessage,HMAC}>，带 ASPSESSIONID cookie。",
    fingerprint: [
      "非 TLS HTTP（默认 profile）",
      "POST 到伪装 profile URL（/en-us/*.html）",
      "body: i=<32hex>&data=<base64 JSON>（GUID/Type/IV/EncryptedMessage/HMAC）",
      "Cookie: ASPSESSIONID=<10hex>; SESSIONID=<固定值>",
      "固定 Chrome 41 UA，周期 check-in（3-5s）",
    ],
    rule: "covenant.http_profile",
    charts: ["covenant_scatter.png"],
  },
  {
    id: "mythic",
    name: "Mythic",
    category: "c2",
    article: 116,
    integrated: true,
    what: "Mythic 是 Docker 化的开源 C2 框架：服务端由 Go 编写，配合 postgres/rabbitmq/hasura，通过独立的 payload type 容器（Athena/Apollo 等）构建各平台 agent。",
    why: "它是当前最活跃的新一代开源 C2 之一：agent 流量默认 AES-256 加密 + HMAC 校验，HTTP profile 把回连伪装成普通网页请求，UI/编排全部容器化，被红队与真实攻击者广泛部署。",
    how: "Athena（C 语言）agent 上线后与 http profile 容器保持一条 Keep-Alive 连接：初始 POST /data（~2.7KB，AES 加密注册信息），之后周期 GET /index?q=<长 base64 密文>（~390B）拉取任务；服务端回 200 + Cache-Control: max-age=0,no-cache 的 JSON，check-in 周期约 10s ± 抖动。",
    fingerprint: [
      "非 TLS HTTP 长连接（Keep-Alive）",
      "初始 POST /data（~2.7KB 加密注册体）",
      "周期 GET /index?q=<长 base64 URL 编码密文>（~390B）",
      "响应 200 + Cache-Control: max-age=0,no-cache，~200B 稳定大小",
      "check-in 周期 ~10s ± 抖动",
    ],
    rule: "mythic.http_checkin",
    charts: ["mythic_scatter.png"],
  },
  {
    id: "cobaltstrike",
    name: "Cobalt Strike",
    category: "c2",
    article: 3,
    integrated: true,
    what: "Cobalt Strike 是商业红队框架，其 beacon（植入体）通过可自定义的 Malleable C2 profile 通信；本实验室用 geacon（Go 对 CS beacon 线协议的字节兼容重实现）复刻其默认 HTTP profile 流量。",
    why: "它是 APT 与真实攻击中最常被观察到的 C2：beacon 的上线 metadata 用 RSA 加密、任务用 AES+HMAC，且 profile 可完全伪装成正常 HTTP，传统特征库极难识别；能检测其协议骨架就意味着抓住了最主流的 C2 形态。",
    how: "beacon 启动生成 16B 会话密钥种子，与系统信息一起用 teamserver 的 RSA 公钥加密（PKCS1v15），base64 后放进 GET /load 的 Cookie 头；服务端解密后回一段 AES-CBC 加密的空任务列表 + HMAC，beacon 按固定间隔（默认 60s，实验室 3s）轮询。",
    fingerprint: [
      "非 TLS HTTP 短流（每条连接一次请求）",
      "GET /load + 超长 Cookie（RSA 加密 metadata ~440B base64）",
      "响应 200 + 固定 32B AES+HMAC 加密体",
      "固定 UA：Mozilla/5.0 (compatible; MSIE 9.0...)",
      "固定间隔轮询（beacon 周期）",
    ],
    rule: "cobaltstrike.beacon_checkin",
    charts: ["cobaltstrike_scatter.png"],
  },
  {
    id: "chopper",
    name: "菜刀 China Chopper",
    category: "webshell",
    article: 1,
    integrated: true,
    what: "菜刀（China Chopper）是最经典的『一句话木马』管理客户端。攻击者把一行 PHP/JSP/ASP 后门（如 `<?php @eval($_POST['z0']);?>`)）写入目标站点，再用菜刀连上去做文件管理、命令执行、数据库操作。",
    why: "它是 Web 入侵后最常用的持久化入口：文件上传与 WebShell 落地之后，菜刀提供图形化的远程控制能力。由于请求体是 base64 包裹的 PHP 代码且字段名固定（z0/z1），它形成了非常稳定的 HTTP 流量形态，也常被其他工具和自动化攻击批量使用。",
    how: "每次操作打开一条短 HTTP 连接（Connection: close），POST 表单字段 z0=base64(PHP eval 代码)、z1=命令/路径参数；服务端 `@eval` 执行后把明文输出作为响应返回。操作完成即断开，无心跳、无会话保持。",
    fingerprint: [
      "非 TLS HTTP POST 短流：操作即连接，无心跳",
      "固定参数名 z0（base64 eval 载荷）与 z1（命令/路径）",
      "请求 500B-2KB（含 @ini_set/@set_time_limit 样板），响应为明文输出",
      "响应带 ->| ... |<- 标记（经典菜刀行为）",
    ],
    rule: "chopper.eval_flow",
    charts: ["chopper_scatter.png"],
  },
  {
    id: "ngrok",
    name: "Ngrok",
    category: "tunnel",
    article: 117,
    integrated: true,
    what: "Ngrok 是使用最广的内网穿透客户端：在本机跑一个 agent，它就会向 ngrok 云建立 TLS 通道，把本地 HTTP/TCP 服务暴露成公网 URL。攻击者常把它用于把受害内网的服务快速拉到公网。",
    why: "它对蓝队是典型的『合法工具滥用』：agent 二进制常见、证书链正规、流量全加密，很难靠黑名单识别；但它始终连接固定的域名 connect.ngrok-agent.com，这个 SNI 是唯一且稳定的标识。",
    how: "agent 启动后以固定 SNI connect.ngrok-agent.com 建立 TLS 会话，认证成功后维持长连接隧道；会话中断时按指数退避（0.5/1/2/4s…）重连，每次重连都是一条新的 TLS 短流。",
    fingerprint: [
      "TLS 短流，固定 SNI connect.ngrok-agent.com",
      "真实客户端 ClientHello ~1.5KB，TLS1.3 密码套件",
      "认证失败/断线时指数退避重连（0.5/1/2/4s）",
      "每次重连一条独立 TLS 流，无跨连接复用",
    ],
    rule: "ngrok.agent_tls",
    charts: ["ngrok_scatter.png"],
  },
  {
    id: "nimplant",
    name: "NimPlant",
    category: "c2",
    article: 125,
    integrated: true,
    what: "NimPlant 是一个用 Nim 编写的 C2 植入体（v2 为 .NET 版本），支持模块化命令和多种回连方式。它的 agent 目标平台是 Windows，本实验室用协议驱动仿真其 HTTP(S) beacon 流量。",
    why: "它代表『编程语言小众化』的 C2 趋势：Nim/.NET 编译的植入体难以被传统杀软静态识别，通信走 HTTPS 加密，检测只能依靠 beacon 的固定节奏与端点特征。",
    how: "agent 启动后按固定周期（默认 60s±抖动）发起一次独立 HTTP(S) 短连接 checkin：POST 到固定 URI，载荷为加密二进制；每次 checkin 一条连接，无 keep-alive，无长连接。",
    fingerprint: [
      "HTTPS beacon 短流：每条连接一次 checkin，无长连接",
      "固定 SNI（实验室 nimplant-c2.local）",
      "POST /api/init + base64 加密二进制载荷",
      "实验室 15s±20% 周期（真实默认 60s±抖动）",
    ],
    rule: "nimplant.beacon",
    charts: ["nimplant_scatter.png"],
  },
  {
    id: "bruteratel",
    name: "Brute Ratel C4",
    category: "c2",
    article: 17,
    integrated: true,
    what: "Brute Ratel C4 是商业攻击框架，其 BADGER 植入体通过可自定义的 C2 profile 通信，默认 sleep 周期约 35-60s。闭源、agent 仅 Windows，本实验室用协议驱动仿真其 HTTPS beacon。",
    why: "它被红队和真实攻击用于绕过 EDR 的检测，流量 profile 可完全塑形（URI、UA、记录大小、顺序均可自定义），但『周期回连 + 固定端点 + 加密载荷』的行为骨架仍然稳定。",
    how: "BADGER 每到一个 sleep 周期就发起一条 HTTPS POST 短连接，把 AES/RSA 加密的命令块上传到 profile 指定端点，取回任务；一次 checkin 一条连接，周期带抖动。",
    fingerprint: [
      "HTTPS POST beacon 短流，无长连接",
      "固定 SNI（实验室 c4-bruteratel.local）",
      "AES/RSA 加密载荷，请求 600-1000B",
      "实验室 20s±15% 周期（真实默认 ~35-60s）",
    ],
    rule: "bruteratel.beacon",
    charts: ["bruteratel_scatter.png"],
  },
  {
    id: "adaptix",
    name: "AdaptixC2",
    category: "c2",
    article: 202,
    integrated: true,
    what: "AdaptixC2 是轻量级红队 C2 框架，服务端可在本实验室容器真实运行（API 登录、BeaconHTTP listener 已验证），自带 beacon agent 仅支持 Windows，agent 侧用协议驱动仿真。",
    why: "它展示了『轻量自研 C2』的典型形态：单端点 HTTP 短流 + RC4 加密载荷 + 固定 checkin 节奏，与传统大框架相比更隐蔽、更易定制。",
    how: "beacon 按固定周期向 HTTP 单端点 POST /checkin，载荷用 RC4 加密后 base64 编码放进固定参数，服务器回包同样加密；每次 checkin 一条短连接。",
    fingerprint: [
      "非 TLS HTTP 单端点短流",
      "POST /checkin + RC4 加密载荷（base64 参数 v）",
      "8s±20% 周期 checkin",
      "请求 300-600B / 响应 200-500B",
    ],
    rule: "adaptix.checkin",
    charts: ["adaptix_scatter.png"],
  },
  {
    id: "simayrat",
    name: "SiMayRAT",
    category: "rat",
    article: 28,
    integrated: true,
    what: "SiMayRAT 是开源的 C# 远控木马，其变种把 C2 藏在云端文档/网盘服务上：受控端假装是文档客户端，HTTPS 轮询云端接口取指令。agent 仅 Windows，本实验室协议驱动仿真。",
    why: "『借道云服务做 C2』是当前最难检测的隐蔽信道之一：目标域名是正常云服务、流量是标准 HTTPS、载荷伪装成文档/JSON，传统域名黑名单完全失效。",
    how: "受控端按固定周期以 HTTPS GET 请求云端文档接口（固定 URI + base64 参数），响应里伪装成 JSON 文档的数据实际是加密指令；无长连接，短轮询。",
    fingerprint: [
      "HTTPS 短轮询，固定周期",
      "固定 SNI（实验室 docs.simayrat.local）",
      "GET /api/documents + base64 载荷（伪装 JSON）",
      "15s±10% 轮询节奏",
    ],
    rule: "simayrat.poll",
    charts: ["simayrat_scatter.png"],
  },
  {
    id: "oceanlotus",
    name: "海莲花 OceanLotus",
    category: "apt",
    article: 175,
    integrated: true,
    what: "海莲花（OceanLotus/APT-C-00）是长期活跃的越南背景 APT，其武器库包含诱饵投递与加密远控木马，C2 通信为 HTTPS 周期回连。闭源，本实验室按公开分析协议驱动仿真。",
    why: "它代表国家级 APT 的典型通信形态：固定 UA/证书、自定义加密、周期回连，行为完全隐藏在正常 HTTPS 中；识别需要组合『SNI + 节奏 + 方向不对称』多个侧信道特征。",
    how: "远控木马每到一个周期就向固定 HTTPS 端点 POST 加密数据（请求显著大于响应），服务器回传加密指令；UA 与证书长期固定，周期带抖动。",
    fingerprint: [
      "HTTPS 远控周期回连",
      "固定 SNI（实验室 cdn.oceanlotus.local）+ 固定 UA（MSIE6）",
      "自定义加密载荷，请求 > 响应",
      "实验室 20s±20% 周期",
    ],
    rule: "oceanlotus.beacon",
    charts: ["oceanlotus_scatter.png"],
  },
  {
    id: "transparenttribe",
    name: "摩诃草 TransparentTribe",
    category: "apt",
    article: 177,
    integrated: true,
    what: "摩诃草（TransparentTribe/APT36）是南亚背景 APT，长期使用借道 Telegram Bot API 等云服务的 C2 信道，把指令藏在消息文本里。闭源，本实验室按公开分析协议驱动仿真。",
    why: "借道 IM 云 API 的 C2 把流量混入海量正常 API 调用，仅靠域名/IP 无法识别；它的弱点在于固定 bot token URI、短轮询节奏和『响应远大于请求』的载荷不对称。",
    how: "受控端以固定短间隔 HTTPS GET 轮询 Telegram 风格接口（/bot<token>/getUpdates），加密指令藏在大段 JSON 消息文本里返回；每次轮询一条短连接。",
    fingerprint: [
      "HTTPS 借道 Telegram 风格 API 短轮询",
      "固定 SNI（实验室 api.telegramtt.local）",
      "GET /bot<token>/getUpdates，载荷在消息文本",
      "10s±10% 轮询节奏，响应显著大于请求",
    ],
    rule: "transparenttribe.poll",
    charts: ["transparenttribe_scatter.png"],
  },
  {
    id: "silenttrinity",
    name: "SILENTTRINITY",
    category: "c2",
    article: 121,
    integrated: true,
    what: "SILENTTRINITY 是基于 IronPython 的 C2：服务端在 Python 里开 gRPC 服务，植入体是 PowerShell 阶段载荷，通信走 HTTP/2 + mTLS，Protobuf 序列化。agent 仅 Windows，本实验室以 HTTPS 长连接周期 checkin 仿真其可观测形态。",
    why: "它是『后渗透框架服务化』的代表：所有命令都变成 gRPC 调用，流量加密且双向认证，传统明文特征失效；但 gRPC 长连接 + 固定节奏的双向小记录在密文侧信道上一眼可辨。",
    how: "stager 与 teamserver 建立 TLS 长连接后按固定节奏双向交换 Protobuf 消息（staging 与 checkin 节奏固定）；连接生命周期长，记录大小稳定。",
    fingerprint: [
      "HTTPS 长连接周期 checkin（仿真 gRPC/HTTP2+mTLS 形态）",
      "固定 SNI（实验室 st-grpc.local）",
      "周期 10s±10%，双向小记录",
      "staging 与 checkin 节奏固定",
    ],
    rule: "silenttrinity.checkin",
    charts: ["silenttrinity_scatter.png"],
  },
  {
    id: "tristealer",
    name: "TriStealer",
    category: "rat",
    article: 157,
    integrated: true,
    what: "TriStealer 是窃密木马：上线与窃密数据外传都以短 HTTP POST 突发完成。闭源，本实验室按公开分析协议驱动仿真。",
    why: "窃密木马的本质是『数据外传』，其流量特征与正常上传截然不同：突发性、上行远大于下行、无心跳节奏。识别它就是在识别数据泄露的信号。",
    how: "感染后先上线注册（短 POST），窃取浏览器/钱包数据后立刻以多条快速 POST 把加密数据外传（2.5-4KB 上行 vs 50-150B 下行），然后静默等待下一轮。",
    fingerprint: [
      "非 TLS HTTP POST 短突发，无固定心跳",
      "上行 2.5-4KB 显著大于下行 50-150B",
      "突发后 20s 空窗",
      "固定端点 POST /upload",
    ],
    rule: "tristealer.exfil_burst",
    charts: ["tristealer_scatter.png"],
  },
  {
    id: "rustystealer",
    name: "RustyStealer",
    category: "rat",
    article: 180,
    integrated: true,
    what: "RustyStealer 是 Ymir 勒索组织使用的 Rust 窃密木马：加密外传短突发，上行为主。闭源，本实验室按公开分析协议驱动仿真。",
    why: "Rust 编写的窃密木马体积小、免杀性强，且外传流量全加密；它的可识别信号是『短生命周期 + 上行突发 + 固定 C2 端点』的组合。",
    how: "受控端把窃取的数据加密后以多条短 HTTPS POST 突发外传到固定端点（3-5KB 上行 vs 60-160B 下行），完成一轮后进入空窗。",
    fingerprint: [
      "HTTPS POST 短突发，上行显著大于下行",
      "固定 SNI（实验室 c2.rustystealer.local）",
      "3-5KB 加密二进制上行 / 60-160B 下行",
      "短生命周期，无心跳",
    ],
    rule: "rustystealer.exfil_burst",
    charts: ["rustystealer_scatter.png"],
  },
  {
    id: "remcos",
    name: "Remcos",
    category: "rat",
    article: 191,
    integrated: true,
    what: "Remcos 是商业远控木马：受控端与 C2 建立 TCP 长连接，用自定义 RC4/XOR 加密帧通信。闭源，本实验室按公开分析协议驱动仿真。",
    why: "它是典型的『商业 RAT 即服务』：功能全、易购买，被大量攻击活动使用。其 TCP 长连接 + 固定帧头 + 周期心跳是稳定的行为指纹。",
    how: "受控端回连 C2 建立长连接，此后按固定周期发送带魔数帧头的小加密帧（心跳/状态上报），服务器回传加密指令。",
    fingerprint: [
      "TCP 长连接回连",
      "固定帧头魔数（REMC）+ 自定义 RC4/XOR 加密帧",
      "12s±15% 周期心跳小包（100-260B）",
      "连接生命周期 = 会话生命周期",
    ],
    rule: "remcos.heartbeat",
    charts: ["remcos_scatter.png"],
  },
  {
    id: "ktlvdoor",
    name: "KTLVdoor",
    category: "rat",
    article: 204,
    integrated: true,
    what: "KTLVdoor 是远控木马：自有协议 TCP 长连接，固定帧头 + 自定义加密，周期心跳。闭源，本实验室按公开分析协议驱动仿真。",
    why: "自有加密协议的 RAT 无法靠特征库识别，只能靠通信结构：长连接、固定帧头、周期心跳小包。",
    how: "受控端与 C2 建立长连接，按固定周期（15s±）发送带 KTLV 帧头的小加密包，维持通道存活并上报状态。",
    fingerprint: [
      "自有协议 TCP 长连接",
      "固定帧头（KTLV）+ 自定义加密",
      "15s±15% 周期心跳（150-350B）",
      "单连接长时间存活",
    ],
    rule: "ktlvdoor.heartbeat",
    charts: ["ktlvdoor_scatter.png"],
  },
  {
    id: "rakshasa",
    name: "Rakshasa",
    category: "tunnel",
    article: 163,
    integrated: true,
    what: "Rakshasa 是多级代理工具：自有加密协议 TCP 长连接，固定帧头/块大小，周期 keepalive。闭源，本实验室按公开分析协议驱动仿真。",
    why: "多级代理是内网横向的核心基础设施，其通道必须长期存活——keepalive 节奏与固定帧结构就是最稳定的检测面。",
    how: "各代理节点之间建立加密 TCP 长连接，按固定周期（20s±）发送固定大小的 keepalive 帧维持链路，数据帧使用固定块大小。",
    fingerprint: [
      "自有加密协议 TCP 长连接",
      "固定帧头（RAKS）+ 固定块大小",
      "20s±15% 周期 keepalive",
      "多级节点之间长连接",
    ],
    rule: "rakshasa.keepalive",
    charts: ["rakshasa_scatter.png"],
  },
  {
    id: "yinhu",
    name: "银狐木马系列",
    category: "rat",
    article: 209,
    integrated: true,
    what: "银狐（Yinhu）是活跃黑产团伙使用的木马系列：UDP 周期小包暗道 + HTTPS 回连双通道，加密载荷，流量规律极强。闭源，本实验室协议驱动仿真其 UDP 暗道通道。",
    why: "黑产木马追求『稳』：UDP 小包暗道几乎不产生可查日志，配合 HTTPS 回连形成双通道；其固定周期与固定包长是强规律性指纹。",
    how: "受控端按固定周期（8s±20%）向 C2 发送固定 48B 的加密 UDP 小包维持通道，同时以 HTTPS 回连同步任务与数据。",
    fingerprint: [
      "UDP 周期 48B 小包暗道（8s±20%）",
      "HTTPS 回连双通道",
      "加密载荷，流量规律性强",
      "双通道互为备份",
    ],
    rule: "yinhu.udp_beacon",
    charts: ["yinhu_scatter.png"],
  },
  {
    id: "manlinghua",
    name: "蔓灵花武器库",
    category: "apt",
    article: 197,
    integrated: true,
    what: "蔓灵花（Manlinghua/Bitter）是多阶段攻击武器库：投递期 HTTP 短流突发，驻留后切换到加密 C2 长连接，阶段切换流量突变。闭源，本实验室按公开分析协议驱动仿真。",
    why: "多阶段是 APT 的标准流程，检测的关键是『阶段切换』：投递期的突发与驻留期的规律心跳在时间轴上形成突变，这种结构变化本身就是信号。",
    how: "阶段一：下载器以 HTTP 短突发拉取后续载荷；阶段二：植入体与 C2 建立 HTTPS 长连接，按 12s±10% 周期 checkin 交换加密数据。",
    fingerprint: [
      "多阶段：投递期 HTTP 短流突发 + 驻留后 HTTPS 长连接 C2",
      "阶段切换流量突变",
      "C2 周期 12s±10%（固定 SNI ml-c2.local）",
      "投递期上行大包 / 驻留期小记录",
    ],
    rule: "manlinghua.c2_phase",
    charts: ["manlinghua_scatter.png"],
  },
  {
    id: "vshell",
    name: "Vshell",
    category: "c2",
    article: 179,
    integrated: true,
    what: "Vshell 是多协议红队主机管理工具（RAT），已无限期停更停发授权。其 agent 通信有 10s 固定心跳、6B 架构标识 + 34B IP 声明、VKey 认证。无官方二进制，本实验室按公开分析协议驱动仿真。",
    why: "它是『红队自研 RAT』的样本：心跳周期固定、声明包结构固定、认证机制私有；这些固定结构在密文侧信道上有明确可测性。",
    how: "agent 与 teamserver 建立 TCP 长连接后按 10s 固定周期发送小帧（架构标识 + IP 声明 + VKey 认证数据），维持通道并上报主机状态。",
    fingerprint: [
      "TCP 长连接",
      "10s 固定心跳小包（40-100B）",
      "6B 架构标识 + 34B IP 声明",
      "VKey 认证（帧头 VSHL）",
    ],
    rule: "vshell.heartbeat",
    charts: ["vshell_scatter.png"],
  },

  {
    id: "vagent",
    name: "Vagent 内存马",
    category: "webshell",
    article: 165,
    integrated: true,
    what: "Vagent 是注入型内存马：Agent 常驻 Web 服务器内存，无文件落盘，通过加密回连与 C2 通信，连接生命周期≈会话生命周期。闭源，本实验室按公开分析协议驱动仿真。",
    why: "内存马是 Web 攻击里最难清理的持久化：不落盘、进程重启即消失，检测窗口只在内存驻留期间；其 HTTPS 长连接 + 周期小包心跳是唯一可观测的稳定信号。",
    how: "注入后 agent 建立 HTTPS 长连接，按固定周期（15s±20%）发送小加密包作为心跳/状态上报，通道随会话生命周期存活。",
    fingerprint: ["HTTPS 长连接（会话级生命周期）", "周期 15s±20% 小包心跳", "固定 SNI（实验室 vagent-c2.local）", "无文件落盘，连接生命周期≈会话生命周期"],
    rule: "vagent.heartbeat",
    charts: ["vagent_scatter.png"],
  },
  {
    id: "evilox",
    name: "EvilOSX",
    category: "c2",
    article: 128,
    integrated: true,
    what: "EvilOSX 是 macOS 后渗透框架：HTTPS 回连、JXA 载荷、周期 checkin，UA 伪装 Mac 浏览器。agent 仅 macOS，本实验室协议驱动仿真。",
    why: "针对 macOS 的 C2 在流量上与普通浏览器流量几乎无差别，但固定周期 checkin + 固定 SNI 的行为骨架可被侧信道识别。",
    how: "agent 以 HTTPS 周期 checkin（20s±20%），载荷为 JXA 脚本加密后上传，UA 伪装 Safari。",
    fingerprint: ["HTTPS 周期 checkin（20s±20%）", "JXA 载荷", "UA 伪装 Mac Safari", "固定 SNI（实验室 evilox-c2.local）"],
    rule: "evilox.checkin",
    charts: ["evilox_scatter.png"],
  },
  {
    id: "octopus",
    name: "Octopus",
    category: "c2",
    article: 124,
    integrated: true,
    what: "Octopus 是 Go 编写的 C2，支持 HTTP(S)/DNS/WebSocket 多传输；其 PowerShell agent 仅 Windows，本实验室以 HTTP beacon 仿真。",
    why: "多协议 C2 是趋势：攻击者会按网络环境切换信道；HTTP beacon 形态下固定端点 + 加密 JSON 载荷 + 周期心跳是稳定指纹。",
    how: "agent 按固定周期（15s±20%）向 HTTP 端点 POST 加密 JSON 载荷（/api/v1/beacon），服务器回传指令。",
    fingerprint: ["非 TLS HTTP beacon（15s±20%）", "POST /api/v1/beacon + 加密 JSON 载荷", "多传输（HTTP(S)/DNS/WebSocket）", "周期心跳"],
    rule: "octopus.beacon",
    charts: ["octopus_scatter.png"],
  },
  {
    id: "sparkrat",
    name: "SparkRat",
    category: "rat",
    article: 188,
    integrated: true,
    what: "SparkRat 是远控木马：HTTP(S) 回连 + 加密载荷，周期上线心跳，UA/URL 固定。闭源，本实验室协议驱动仿真。",
    why: "固定 UA/URL + 固定周期是中小型木马的典型弱点：只要端点不变，节奏就完全可预测。",
    how: "受控端按固定周期（10s±20%）向固定端点 POST 加密上线心跳（/spark/check）。",
    fingerprint: ["HTTP 周期上线心跳（10s±20%）", "固定 UA/URL（POST /spark/check）", "加密载荷"],
    rule: "sparkrat.beacon",
    charts: ["sparkrat_scatter.png"],
  },
  {
    id: "ksrat",
    name: "KSRAT",
    category: "rat",
    article: 158,
    integrated: true,
    what: "KSRAT 是海莲花（APT-C-12）使用的远控木马：HTTP POST 分钟级周期回连，自定义加密载荷，固定 UA/URL。闭源，本实验室协议驱动仿真（周期缩短）。",
    why: "APT 对木马的要求是稳：低频长周期回连降低暴露面；但一旦节奏和端点被摸清，检测就变得确定。",
    how: "受控端以分钟级周期向固定 URL POST 加密数据（实验室 20s±15%），保持上线与指令轮询。",
    fingerprint: ["HTTP POST 分钟级周期回连（实验室 20s±15%）", "自定义加密载荷", "固定 UA/URL（/ks/login）"],
    rule: "ksrat.beacon",
    charts: ["ksrat_scatter.png"],
  },
  {
    id: "loki",
    name: "Loki 远控",
    category: "rat",
    article: 196,
    integrated: true,
    what: "Loki 远控：HTTP(S) 周期回连，加密载荷，短流 + 心跳节奏。闭源，本实验室协议驱动仿真。",
    why: "短流回连型木马每次通信都新建连接，难以从连接维度聚合，但周期节奏和端点特征依然可辨。",
    how: "受控端以固定周期（15s±20%）发起短 HTTP 回连（/loki/status），上传加密心跳。",
    fingerprint: ["HTTP 周期回连短流（15s±20%）", "加密载荷", "POST /loki/status 心跳节奏"],
    rule: "loki.beacon",
    charts: ["loki_scatter.png"],
  },
  {
    id: "zloader",
    name: "Zloader",
    category: "rat",
    article: 199,
    integrated: true,
    what: "Zloader 是银行木马家族：HTTPS 回连 + 模块下载突发，周期 C2 心跳，配置/载荷加密。闭源，本实验室协议驱动仿真。",
    why: "模块化银行木马不仅回连 C2，还会下载新模块——响应显著大于请求的周期性 HTTPS 流是它的独特信号。",
    how: "agent 周期（15s±20%）HTTPS 心跳 C2，同时按需拉取大模块（响应 800-1500B 显著大于请求）。",
    fingerprint: ["HTTPS 周期 C2 心跳（15s±20%）+ 模块下载", "响应（800-1500B）显著大于请求", "固定 SNI（实验室 zloader-c2.local）", "配置/载荷加密"],
    rule: "zloader.beacon",
    charts: ["zloader_scatter.png"],
  },
  {
    id: "wmrat",
    name: "wmRAT",
    category: "rat",
    article: 126,
    integrated: true,
    what: "wmRAT 是蔓灵花组织远控木马：HTTP POST 周期回连，3DES 等自定义加密载荷，UA/URL 固定。闭源，本实验室协议驱动仿真。",
    why: "组织级 RAT 通常沿用固定基础设施，端点与节奏的稳定性让行为检测非常可靠。",
    how: "受控端以固定周期（12s±20%）向固定端点 POST 3DES 加密数据（/wm/update）。",
    fingerprint: ["HTTP POST 周期回连（12s±20%）", "3DES 等自定义加密载荷", "固定 UA/URL（/wm/update）"],
    rule: "wmrat.beacon",
    charts: ["wmrat_scatter.png"],
  },
  {
    id: "badnews",
    name: "BADNEWS",
    category: "rat",
    article: 138,
    integrated: true,
    what: "BADNEWS 是白象组织木马：HTTP 分钟级周期回连，加密载荷，固定 URL/UA。闭源，本实验室协议驱动仿真（周期缩短）。",
    why: "低频长周期回连是规避检测的常用手段，实验室缩短周期以可测，真实场景需更长观察窗。",
    how: "受控端以分钟级周期向固定 URL 回连（实验室 20s±15%），上传加密状态。",
    fingerprint: ["HTTP 分钟级周期回连（实验室 20s±15%）", "加密载荷", "固定 URL/UA（/news/check）"],
    rule: "badnews.beacon",
    charts: ["badnews_scatter.png"],
  },
  {
    id: "perfspyrat",
    name: "PerfSpyRAT",
    category: "rat",
    article: 173,
    integrated: true,
    what: "PerfSpyRAT 是海莲花远控木马：HTTP 周期回连，加密载荷，短流节奏固定。闭源，本实验室协议驱动仿真。",
    why: "节奏固定的短流回连即使每次包都加密，其时间规律也足以与正常流量区分。",
    how: "受控端按固定节奏（10s±20%）发起短 HTTP 回连（/perf/report）。",
    fingerprint: ["HTTP 周期回连（10s±20%）", "加密载荷", "短流节奏固定（/perf/report）"],
    rule: "perfspyrat.beacon",
    charts: ["perfspyrat_scatter.png"],
  },
  {
    id: "fatalrat",
    name: "FatalRAT",
    category: "rat",
    article: 7,
    integrated: true,
    what: "FatalRAT 是针对中国的远控木马：HTTP 短流周期回连，加密载荷，心跳间隔稳定。闭源，本实验室协议驱动仿真。",
    why: "心跳间隔稳定是它的指纹核心：越稳定的节奏越容易被行为检测锁定。",
    how: "受控端以稳定间隔（12s±15%）POST 加密数据（/fatal/check）。",
    fingerprint: ["HTTP 短流周期回连（12s±15%）", "心跳间隔稳定", "POST /fatal/check"],
    rule: "fatalrat.beacon",
    charts: ["fatalrat_scatter.png"],
  },
  {
    id: "sidewinder",
    name: "响尾蛇 SideWinder",
    category: "apt",
    article: 22,
    integrated: true,
    what: "响尾蛇（SideWinder）是南亚 APT：投递期 HTTP 下载突发，C2 为 HTTPS 周期短流，加密载荷。闭源，本实验室多阶段协议驱动仿真。",
    why: "投递与驻留两个阶段的流量形态完全不同——识别阶段切换本身就是检测 APT 的关键信号。",
    how: "阶段一：下载器以 HTTP 突发拉取载荷；阶段二：植入体与 HTTPS C2 建立长连接，按 12s±10% checkin。",
    fingerprint: ["多阶段：投递期 HTTP 下载突发 + C2 HTTPS 周期短流", "C2 长连接 12s±10%（SNI sidewinder-c2.local）", "加密载荷"],
    rule: "sidewinder.c2_phase",
    charts: ["sidewinder_scatter.png"],
  },
  {
    id: "aptc60",
    name: "伪猎者 APT-C-60",
    category: "apt",
    article: 171,
    integrated: true,
    what: "伪猎者（APT-C-60）借道云盘/网盘 HTTPS 做加密 C2：周期轮询，载荷加密。闭源，本实验室协议驱动仿真。",
    why: "借道公共云盘的 C2 让域名白名单失效，但固定轮询周期与固定 SNI 仍然可测。",
    how: "受控端以固定周期（20s±20%）HTTPS 轮询网盘风格接口（/api/list，SNI pan.aptc60.local）。",
    fingerprint: ["借道云盘/网盘 HTTPS 加密 C2", "周期轮询 20s±20%", "固定 SNI（实验室 pan.aptc60.local）"],
    rule: "aptc60.poll",
    charts: ["aptc60_scatter.png"],
  },
  {
    id: "aptc68",
    name: "寄生虫 APT-C-68",
    category: "apt",
    article: 167,
    integrated: true,
    what: "寄生虫（APT-C-68）：多阶段投递 + HTTPS 加密回连，周期心跳，载荷加密。闭源，本实验室协议驱动仿真。",
    why: "多阶段投递体现组织化运营，驻留期的规律心跳是稳定的检测面。",
    how: "投递后植入体以 HTTPS 周期心跳（15s±20%）回连 C2（/checkin）。",
    fingerprint: ["多阶段投递 + HTTPS 加密回连（15s±20%）", "周期心跳", "固定 SNI（实验室 aptc68-c2.local）"],
    rule: "aptc68.beacon",
    charts: ["aptc68_scatter.png"],
  },
  {
    id: "hemao",
    name: "黑猫团伙",
    category: "apt",
    article: 193,
    integrated: true,
    what: "黑猫团伙（Hemaoyuan）攻击武器：HTTPS 加密回连，周期心跳，UA/URL 固定。闭源，本实验室协议驱动仿真。",
    why: "黑产团伙的武器复用度高，固定 UA/URL/周期形成可重复识别的行为签名。",
    how: "受控端以 HTTPS 周期心跳（15s±15%）回连固定端点（/status）。",
    fingerprint: ["HTTPS 加密回连（15s±15%）", "周期心跳", "UA/URL 固定（SNI hemao-c2.local）"],
    rule: "hemao.beacon",
    charts: ["hemao_scatter.png"],
  },
  {
    id: "lazarus",
    name: "Lazarus",
    category: "apt",
    article: 9,
    integrated: true,
    what: "Lazarus 以木马化开源软件投递恶意载荷，C2 为 HTTPS 加密回连，beacon 周期 + 抖动。闭源，本实验室协议驱动仿真。",
    why: "国家级 APT 的 beacon 会刻意加抖动对抗周期性检测——因此检测需要容忍带宽内的间隔波动。",
    how: "受控端以 25s±30% 的抖动周期 HTTPS 回连 C2（/api/beacon）。",
    fingerprint: ["HTTPS 加密 C2 回连（25s±30%）", "beacon 周期 + 抖动", "固定 SNI（实验室 lazarus-c2.local）"],
    rule: "lazarus.beacon",
    charts: ["lazarus_scatter.png"],
  },
  {
    id: "apt29",
    name: "APT29",
    category: "apt",
    article: 6,
    integrated: true,
    what: "APT29（Cozy Bear）常借道 Cobalt Strike 等 beacon 型 C2：HTTPS 回连，周期 + 抖动，载荷加密。闭源，本实验室协议驱动仿真。",
    why: "beacon 型 HTTPS 回连是国家级 APT 的主流形态；它与 Cobalt Strike 的差异在于节奏、UA 与端点，需要组合特征区分。",
    how: "beacon 以 20s±25% 抖动周期 HTTPS 回连（/load），加密载荷。",
    fingerprint: ["beacon 型 HTTPS 回连（20s±25%）", "周期 + 抖动", "载荷加密（SNI apt29-c2.local）"],
    rule: "apt29.beacon",
    charts: ["apt29_scatter.png"],
  },
  {
    id: "oilrig",
    name: "OilRig",
    category: "apt",
    article: 16,
    integrated: true,
    what: "OilRig 使用 PowerShell 后门：HTTP(S) 周期回连 + DNS 隧道备用，载荷加密。闭源，本实验室协议驱动仿真。",
    why: "PowerShell 后门无文件落盘，且主信道与备用信道并存——检测主信道的规律回连即可。",
    how: "PowerShell 后门以 HTTP 周期回连（18s±20%，/ps/run），DNS 隧道作为备用信道。",
    fingerprint: ["PowerShell 后门 HTTP 周期回连（18s±20%）", "加密载荷", "POST /ps/run + DNS 隧道备用"],
    rule: "oilrig.beacon",
    charts: ["oilrig_scatter.png"],
  },
  {
    id: "donot",
    name: "Donot",
    category: "apt",
    article: 11,
    integrated: true,
    what: "Donot（肚脑虫）多阶段 HTTP(S) 通信，RC4 等加密载荷，URL/UA 随阶段变化。闭源，本实验室多阶段协议驱动仿真。",
    why: "URL/UA 随阶段变化是规避特征库的手段，但阶段本身（投递→驻留）的结构变化可被检测。",
    how: "阶段一 HTTP 突发投递；阶段二与 HTTPS C2 建立长连接，14s±10% checkin。",
    fingerprint: ["多阶段 HTTP(S) 通信", "RC4 等加密载荷", "URL/UA 随阶段变化（C2 HTTPS 14s±10%）"],
    rule: "donot.c2_phase",
    charts: ["donot_scatter.png"],
  },
  {
    id: "ghostwriter",
    name: "Ghostwriter",
    category: "apt",
    article: 29,
    integrated: true,
    what: "Ghostwriter（幽灵笔手）借道云存储 HTTPS 做加密 C2：周期轮询，载荷伪装文件。闭源，本实验室协议驱动仿真。",
    why: "借道云存储的 C2 流量与正常文件同步几乎一致，固定轮询周期与端点 SNI 是仅存的稳定指纹。",
    how: "受控端以 22s±20% 周期 HTTPS 轮询云存储风格接口（/files，SNI drive.ghostwriter.local）。",
    fingerprint: ["借道云存储 HTTPS 加密 C2", "周期轮询 22s±20%", "载荷伪装文件（SNI drive.ghostwriter.local）"],
    rule: "ghostwriter.poll",
    charts: ["ghostwriter_scatter.png"],
  },
];
